require('dotenv').config()

const VALOR_VERMELHO = parseFloat(process.env.VALOR_VERMELHO) || 25
const PREMIO_VERDE = parseFloat(process.env.PREMIO_VERDE) || 100
const TOTAL_VERMELHOS = 8
const TAXA_INDICACAO_PERCENTUAL = 0.2
const COMISSAO_INDICACAO = VALOR_VERMELHO * TAXA_INDICACAO_PERCENTUAL
const TAXA_PIX = parseFloat(process.env.ABACATE_PIX_FEE) || 0.8
const VALOR_MINIMO_SAQUE = PREMIO_VERDE
const TOTAL_ARRECADADO = VALOR_VERMELHO * TOTAL_VERMELHOS
const MARGEM_PLATAFORMA =
  TOTAL_ARRECADADO - PREMIO_VERDE - COMISSAO_INDICACAO * TOTAL_VERMELHOS

function formatarMoeda(valor) {
  return new Intl.NumberFormat('pt-BR', {
    style: 'currency',
    currency: 'BRL'
  }).format(Number(valor) || 0)
}

const VALOR_VERMELHO_TEXTO = formatarMoeda(VALOR_VERMELHO)
const PREMIO_VERDE_TEXTO = formatarMoeda(PREMIO_VERDE)
const COMISSAO_INDICACAO_TEXTO = formatarMoeda(COMISSAO_INDICACAO)

module.exports = {
  VALOR_VERMELHO,
  PREMIO_VERDE,
  TOTAL_VERMELHOS,
  TOTAL_ARRECADADO,
  MARGEM_PLATAFORMA,
  TAXA_PIX,
  VALOR_MINIMO_SAQUE,
  VALOR_VERMELHO_TEXTO,
  PREMIO_VERDE_TEXTO,
  COMISSAO_INDICACAO,
  COMISSAO_INDICACAO_TEXTO,
  TAXA_INDICACAO_PERCENTUAL,
  formatarMoeda,
  MOEDA: 'BRL'
}